# Generated by Django 5.2.7 on 2025-10-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_contactmessage_faq_project_alter_service_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='long',
            field=models.TextField(default='description of the service'),
        ),
        migrations.AddField(
            model_name='service',
            name='short',
            field=models.CharField(default='brief description of the service', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(help_text='Use a Lucide icon name or FontAwesome icon class', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
