# Generated by Django 5.2.7 on 2025-10-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_service_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.AddField(
            model_name='service',
            name='faqs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
